pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('achat') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

    
        stage('Test') {
            steps {
                dir('achat') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'achat/**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'achat/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build en échec.'
        }
    }
}