pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('achat') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

    
        stage('SonarQube Analysis') {
            steps {
                dir('achat') {
                    withSonarQubeEnv('sonar') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('achat') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'achat/**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Nexus Upload') {
            steps {
                dir('achat') {
                    sh 'mvn deploy -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build en échec.'
        }
    }
}